=== nathdolan/better-forms/api/bf-formtemplate-api/schemas/bf-formtemplate-schema.json
{
  "id": "http://hmrc.gov.uk/jsonschema/bf-formtemplate#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Schema for a BetterForms Form Template",
    "type": "object",
      "properties": {
        "formTypeId": {
          "type": "string"
        },
        "formName": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "archived": {
          "type": "boolean"
        },
        "characterSet": {
          "type": "string"
        },
        "submitTargets": {
          "type": "string"
        },
        "submitSuccessUrl": {
          "type": "string"
        },
        "submitErrorUrl": {
          "type": "string"
        },
        "sections": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string"
              },
              "fields": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "label": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    },
                    "format": {
                      "type": "string"
                    },
                    "helpText": {
                      "type": "string"
                    },
                    "readonly": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "label"
                  ]
                }
              }
            },
            "required": [
              "title",
              "fields"
            ]
          }
        }
      },
      "required": [
        "formTypeId",
        "formName",
        "version",
        "sections"
      ]
}

=== nathdolan/better-forms/api/bf-formtemplate-api/examples/bf-list-of-formtemplate-ipt100s.json
[
  {
    "formTypeId": "IPT100",
    "formName": "Insurance Premium Tax Return | Yswiriant Ffurflen Dreth Premiwm",
    "version": "0.1.0",
    "description": "Fill in your insurance premium tax return form online | Llenwch eich ffurflen dreth premiwm yswiriant ar-lein",
    "characterSet": "UTF-8",
    "submitTargets": "dms",
    "submitSuccessUrl": "http://www.google.co.uk",
    "submitErrorUrl": "http://www.yahoo.co.uk",
    "sections": [
      {
        "title": "Your details | eich manylion",
        "fields": [
          {
            "id": "iptRegNum",
            "label": "Insurance Premium Tax (IPT) registration number | Treth Premiwm Yswiriant (IPT) rhif cofrestru",
            "readonly": "true",
            "mandatory": "true"
          }
        ]
      },
      {
        "title": "About you | Amdanat ti",
        "description": "This information is about the person completing the form | Mae'r wybodaeth hon am y person sy'n llenwi'r ffurflen",
        "fields": [
          {
            "id": "firstName",
            "label": "Your first name | Eich enw cyntaf",
            "mandatory": "true"
          },
          {
            "id": "lastName",
            "label": "Your last name | Eich enw olaf",
            "mandatory": "true"
          },
          {
            "id": "telephoneNumber",
            "label": "Telephone number | Eich enw olaf",
            "helpText": "If this is a UK landline or an overseas number, you must include the area or dialling code. | Os yw hyn yn llinell tir neu rif tramor y DU, rhaid i chi gynnwys yr ardal neu'r cod deialu.",
            "format": "telephoneNumber",
            "mandatory": "true"
          },
          {
            "id": "status",
            "label": "Status | statws",
            "helpText": "For example: director, company secretary, agent | Er enghraifft: gyfarwyddwr, ysgrifennydd cwmni, asiant",
            "mandatory": "true"
          }
        ]
      },
      {
        "title": "Business details | manylion Busnes",
        "fields": [
          {
            "id": "nameOfBusiness",
            "label": "Name of business | Enw'r busnes",
            "mandatory": "true"
          },
          {
            "id": "accountingPeriodStartDate",
            "label": "Accounting period start date | Dyddiad dechrau'r cyfnod cyfrifeg",
            "format": "date",
            "mandatory": "true"
          },
          {
            "id": "accountingPeriodEndDate",
            "label": "Accounting period end date | Dyddiad diwedd cyfnod Cyfrifeg",
            "format": "date",
            "mandatory": "true"
          }
        ]
      },
      {
        "title": "Rate for the period of the Insurance Premium Tax | Gyfradd ar gyfer y cyfnod y Dreth Premiwm Yswiriant",
        "fields": [
          {
            "id": "standardRateIPTDueForThisPeriod",
            "label": "Standard rate IPT due for this period | Cyfradd safonol IPT sy'n ddyledus am y cyfnod hwn",
            "helpText": "You should deduct any standard credits which are due to you | Dylech ddidynnu unrhyw gredydau safonol sydd yn ddyledus i chi",
            "format": "sterling",
            "mandatory": "true"
          },
          {
            "id": "higherRateIPTDueForThisPeriod",
            "label": "Higher rate IPT due for this period | Cyfradd uwch IPT sy'n ddyledus am y cyfnod hwn",
            "format": "sterling",
            "mandatory": "true"
          }
        ]
      }
    ]
  },
  
  {
    "formTypeId": "IPT100",
    "formName": "Insurance Premium Tax Return | Yswiriant Ffurflen Dreth Premiwm",
    "version": "0.1.0",
    "description": "Fill in your insurance premium tax return form online | Llenwch eich ffurflen dreth premiwm yswiriant ar-lein",
    "characterSet": "UTF-8",
    "submitTargets": "dms",
    "submitSuccessUrl": "http://www.google.co.uk",
    "submitErrorUrl": "http://www.yahoo.co.uk",
    "sections": [
      {
        "title": "Your details | eich manylion",
        "fields": [
          {
            "id": "iptRegNum",
            "label": "Insurance Premium Tax (IPT) registration number | Treth Premiwm Yswiriant (IPT) rhif cofrestru",
            "readonly": "true",
            "mandatory": "true"
          }
        ]
      },
      {
        "title": "About you | Amdanat ti",
        "description": "This information is about the person completing the form | Mae'r wybodaeth hon am y person sy'n llenwi'r ffurflen",
        "fields": [
          {
            "id": "firstName",
            "label": "Your first name | Eich enw cyntaf",
            "mandatory": "true"
          },
          {
            "id": "lastName",
            "label": "Your last name | Eich enw olaf",
            "mandatory": "true"
          },
          {
            "id": "telephoneNumber",
            "label": "Telephone number | Eich enw olaf",
            "helpText": "-If this is a UK landline or an overseas number, you must include the area or dialling code. | Os yw hyn yn llinell tir neu rif tramor y DU, rhaid i chi gynnwys yr ardal neu'r cod deialu.",
            "format": "telephoneNumber",
            "mandatory": "true"
          },
          {
            "id": "status",
            "label": "Status | statws",
            "helpText": "For example: director, company secretary, agent | Er enghraifft: gyfarwyddwr, ysgrifennydd cwmni, asiant",
            "mandatory": "true"
          }
        ]
      },
      {
        "title": "Business details | manylion Busnes",
        "fields": [
          {
            "id": "nameOfBusiness",
            "label": "Name of business | Enw'r busnes",
            "mandatory": "true"
          },
          {
            "id": "accountingPeriodStartDate",
            "label": "Accounting period start date | Dyddiad dechrau'r cyfnod cyfrifeg",
            "format": "date",
            "mandatory": "true"
          },
          {
            "id": "accountingPeriodEndDate",
            "label": "Accounting period end date | Dyddiad diwedd cyfnod Cyfrifeg",
            "format": "date",
            "mandatory": "true"
          }
        ]
      },
      {
        "title": "Rate for the period of the Insurance Premium Tax | Gyfradd ar gyfer y cyfnod y Dreth Premiwm Yswiriant",
        "fields": [
          {
            "id": "standardRateIPTDueForThisPeriod",
            "label": "Standard rate IPT due for this period | Cyfradd safonol IPT sy'n ddyledus am y cyfnod hwn",
            "helpText": "You should deduct any standard credits which are due to you | Dylech ddidynnu unrhyw gredydau safonol sydd yn ddyledus i chi",
            "format": "sterling",
            "mandatory": "true"
          },
          {
            "id": "higherRateIPTDueForThisPeriod",
            "label": "Higher rate IPT due for this period | Cyfradd uwch IPT sy'n ddyledus am y cyfnod hwn",
            "format": "sterling",
            "mandatory": "true"
          }
        ]
      }
    ]
  }
]
